-- PlaceIQ Company Seed Data — 40+ Indian & Global Companies
-- Runs automatically on startup via spring.sql.init.mode=always

INSERT IGNORE INTO companies (name, category, description, min_fresher_ctc, max_fresher_ctc, hiring_months, interview_rounds, top_skills, job_keywords, pyq_links, logo_url) VALUES

-- ============================================
-- SERVICE COMPANIES
-- ============================================
('TCS', 'Service',
 'Tata Consultancy Services — India''s largest IT services and consulting company. Hires ~40,000 freshers annually.',
 3.5, 7.0,
 'Dec-Feb, Jul-Sep',
 'TCS NQT (Aptitude + Coding), Technical Interview, Managerial Interview, HR Interview',
 'DSA,Java,C++,SQL,OOPs,DBMS,Networking,Verbal Reasoning,Aptitude,Problem Solving',
 'systems engineer,software engineer,developer,analyst,associate',
 'https://www.geeksforgeeks.org/tcs-interview-questions/',
 NULL),

('Infosys', 'Service',
 'Infosys — Leading global IT services, consulting, and outsourcing company based in Pune.',
 3.6, 8.0,
 'Dec-Feb, Jul-Sep',
 'InfyTQ / HackWithInfy Assessment, Technical Interview, HR Round',
 'Java,Python,SQL,OOPs,DSA,Communication,Agile,System Thinking,Logical Reasoning,Data Structures',
 'systems engineer,technology analyst,digital specialist,power programmer',
 'https://www.geeksforgeeks.org/infosys-interview-experience/',
 NULL),

('Wipro', 'Service',
 'Wipro — Global IT, consulting, and business process services company.',
 3.5, 6.5,
 'Nov-Jan, Jun-Aug',
 'NLTH Online Test, Technical Interview, Verbal Ability, HR Round',
 'Java,Python,SQL,Networking,DBMS,OOPs,Communication,Aptitude,Testing,Git',
 'project engineer,test engineer,developer,analyst',
 'https://www.geeksforgeeks.org/wipro-interview-experience/',
 NULL),

('Cognizant', 'Service',
 'Cognizant — American multinational IT services and consulting company.',
 4.0, 7.5,
 'Oct-Feb, Jun-Aug',
 'CognizantOnCampus Test, Technical Interview, HR Round',
 'Java,SQL,Python,DSA,OOPs,Communication,Agile,Cloud Basics,Testing,Problem Solving',
 'programmer analyst,GET,associate,junior analyst',
 'https://www.geeksforgeeks.org/cognizant-interview-experience/',
 NULL),

('HCL', 'Service',
 'HCL Technologies — Leading global technology company delivering enterprise IT solutions.',
 3.5, 6.0,
 'Nov-Mar, Jul-Sep',
 'HCL TechBee Test, Technical Interview, HR Round',
 'Java,C++,SQL,Networking,OOPs,Linux,Testing,Communication,Git,DBMS',
 'engineer,developer,analyst,associate consultant',
 'https://www.geeksforgeeks.org/hcl-interview-experience/',
 NULL),

('Capgemini', 'Service',
 'Capgemini — Global leader in partnering with companies to transform their businesses through intelligent technology.',
 3.8, 7.0,
 'Oct-Feb',
 'Pseudo Code Test, Behavioral Assessment, Technical Interview, HR Round',
 'Java,Python,SQL,Pseudocode,OOPs,Communication,Aptitude,Excel,Analytics,Problem Solving',
 'analyst,associate consultant,developer,fresher engineer',
 'https://www.geeksforgeeks.org/capgemini-interview-experience/',
 NULL),

('Tech Mahindra', 'Service',
 'Tech Mahindra — Indian multinational offering IT services, solutions, and business process outsourcing.',
 3.5, 6.0,
 'Nov-Mar',
 'Online Test (Aptitude + Coding), Technical Interview, HR Round',
 'Java,SQL,Networking,OOPs,Communication,Aptitude,Testing,Linux,Git,DBMS',
 'software engineer,associate engineer,developer,support engineer',
 'https://www.geeksforgeeks.org/tech-mahindra-interview-experience/',
 NULL),

('Mphasis', 'Service',
 'Mphasis — IT solutions provider specializing in cloud and cognitive services for banking and capital markets.',
 4.0, 7.0,
 'Nov-Feb',
 'Coding Test, Technical Interview, Manager Interview, HR Round',
 'Java,SQL,Python,OOPs,Communication,Agile,Testing,Cloud,Git,Analytics',
 'junior engineer,software developer,analyst,associate',
 'https://www.geeksforgeeks.org/mphasis-interview-experience/',
 NULL),

('LTIMindtree', 'Service',
 'LTIMindtree — Global technology consulting and digital solutions company formed by merger of LTI and Mindtree.',
 4.5, 8.5,
 'Oct-Mar',
 'LCAT Aptitude Test, Coding Round, Technical Interview (2), HR Round',
 'Java,Python,SQL,DSA,OOPs,System Design,Cloud,Agile,Git,Communication',
 'software engineer,developer,analyst,cloud engineer',
 'https://www.geeksforgeeks.org/ltimindtree-interview-question/',
 NULL),

-- ============================================
-- PRODUCT COMPANIES
-- ============================================
('Zoho', 'Product',
 'Zoho Corporation — Indian SaaS company with 50+ business software products used globally.',
 3.5, 12.0,
 'Nov-Apr',
 'Written Programming Test, Technical Rounds (3-4), HR Discussion',
 'Java,C++,DSA,SQL,Problem Solving,OOPs,System Design,Algorithms,Data Structures,Communication',
 'member technical staff,software developer,product engineer',
 'https://www.geeksforgeeks.org/zoho-interview-experience/',
 NULL),

('Freshworks', 'Product',
 'Freshworks — SaaS company building customer engagement software used by 60,000+ businesses.',
 6.0, 14.0,
 'Oct-Mar',
 'Online Coding Test, Technical Rounds (3), System Design, HR Round',
 'Java,Python,React,SQL,DSA,System Design,OOPs,Git,REST API,Communication',
 'software development engineer,product engineer,fullstack developer',
 'https://www.geeksforgeeks.org/freshworks-interview-experience/',
 NULL),

('BYJU''S', 'Product',
 'BYJU''S — World''s leading EdTech company revolutionizing learning with personalized programs.',
 5.0, 10.0,
 'Sep-Feb',
 'Online Test, Technical Interview, HR Round',
 'Java,Python,SQL,React,Communication,Data Analysis,Machine Learning,OOPs,Git,REST API',
 'software engineer,product analyst,data analyst,content developer',
 'https://www.geeksforgeeks.org/byjus-interview-experience/',
 NULL),

('Razorpay', 'Product',
 'Razorpay — India''s leading full-stack financial solutions company. Processes $60B+ annually.',
 8.0, 18.0,
 'Oct-Mar',
 'Resume Shortlist, Coding Round, System Design, Technical (2), HR',
 'Java,Python,Go,System Design,DSA,SQL,Microservices,Docker,AWS,Communication',
 'software development engineer,backend engineer,platform engineer',
 'https://www.geeksforgeeks.org/razorpay-interview-experience/',
 NULL),

('Swiggy', 'Product',
 'Swiggy — India''s leading on-demand food delivery and quick commerce platform.',
 8.0, 20.0,
 'Sep-Feb',
 'Online Coding Test, Technical Rounds (3), System Design, HR',
 'Java,Python,DSA,System Design,SQL,Microservices,AWS,Docker,Kubernetes,Communication',
 'software development engineer,backend engineer,data engineer',
 'https://www.geeksforgeeks.org/swiggy-interview-experience/',
 NULL),

('Zomato', 'Product',
 'Zomato — Restaurant discovery, food delivery, and quick commerce platform operating in 1000+ cities.',
 7.0, 18.0,
 'Sep-Mar',
 'Coding Test, Technical Rounds (3), System Design, HR',
 'Java,Python,DSA,System Design,SQL,React,AWS,Docker,Communication,Problem Solving',
 'software development engineer,data engineer,product analyst',
 'https://www.geeksforgeeks.org/zomato-interview-experience/',
 NULL),

('Meesho', 'Product',
 'Meesho — Social commerce platform enabling small businesses to sell online via WhatsApp and social media.',
 7.0, 16.0,
 'Sep-Feb',
 'Online Coding Test, Technical Rounds (3), System Design, HR',
 'Java,Python,DSA,SQL,System Design,Microservices,AWS,React,Git,Communication',
 'software engineer,product engineer,backend developer',
 'https://www.geeksforgeeks.org/meesho-interview-experience/',
 NULL),

('PhonePe', 'Product',
 'PhonePe — India''s leading digital payments platform with 500M+ registered users.',
 8.0, 20.0,
 'Oct-Feb',
 'Online Coding Test, Technical Rounds (3), System Design, HR',
 'Java,Python,DSA,System Design,SQL,Microservices,Kafka,AWS,Docker,Communication',
 'software development engineer,platform engineer,data engineer',
 'https://www.geeksforgeeks.org/phonepe-interview-experience/',
 NULL),

('Paytm', 'Product',
 'Paytm — Multi-service financial platform offering payments, banking, lending, and insurance.',
 6.0, 15.0,
 'Sep-Mar',
 'Online Coding Test, Technical Rounds (2-3), System Design, HR',
 'Java,Python,SQL,DSA,System Design,AWS,React,OOPs,Git,Communication',
 'software engineer,backend developer,analyst,data engineer',
 'https://www.geeksforgeeks.org/paytm-interview-experience/',
 NULL),

-- ============================================
-- GLOBAL MNCs
-- ============================================
('Amazon', 'MNC',
 'Amazon — World''s largest e-commerce and cloud computing company. AWS powers 33% of the internet.',
 12.0, 30.0,
 'Sep-Nov, Feb-Apr',
 'Online Assessment (Coding + Work Simulation), Technical Rounds (4-5), Bar Raiser, HR',
 'DSA,System Design,Java,Python,Leadership Principles,SQL,AWS,Problem Solving,OOPs,Algorithms',
 'SDE,software development engineer,cloud support engineer,solutions architect',
 'https://www.geeksforgeeks.org/amazon-interview-experience/',
 NULL),

('Google', 'MNC',
 'Google — Multinational technology company specializing in Internet services, AI, and cloud computing.',
 20.0, 50.0,
 'Year Round',
 'Phone Screen (2), Onsite Technical Rounds (4-5), Committee Review, Offer',
 'DSA,Algorithms,System Design,Java,Python,C++,Problem Solving,Mathematics,Distributed Systems,Communication',
 'software engineer,site reliability engineer,data scientist,ML engineer',
 'https://www.geeksforgeeks.org/google-interview-experience/',
 NULL),

('Microsoft', 'MNC',
 'Microsoft — Multinational technology corporation producing software, devices, and cloud services.',
 15.0, 35.0,
 'Aug-Nov, Feb-Apr',
 'Online Assessment, Technical Rounds (4-5 incl. loop), HR',
 'DSA,System Design,Java,C#,Azure,Problem Solving,OOPs,SQL,Communication,Algorithms',
 'SDE,software engineer,program manager,cloud engineer',
 'https://www.geeksforgeeks.org/microsoft-interview-experience/',
 NULL),

('Meta', 'MNC',
 'Meta — Social media and technology conglomerate operating Facebook, Instagram, WhatsApp, and VR platforms.',
 18.0, 45.0,
 'Sep-Nov, Mar-May',
 'Phone Screen, Coding Rounds (2), System Design, Behavioral, HR',
 'DSA,System Design,Python,Java,React,SQL,Problem Solving,Algorithms,Distributed Systems,Communication',
 'software engineer,production engineer,data engineer,ML engineer',
 'https://www.geeksforgeeks.org/facebook-interview-experience/',
 NULL),

('Adobe', 'MNC',
 'Adobe — Multinational computer software company known for creative tools and PDF technology.',
 10.0, 25.0,
 'Sep-Feb',
 'Online Test, Technical Rounds (3-4), Hiring Manager, HR',
 'Java,Python,DSA,System Design,SQL,AWS,React,OOPs,Git,Communication',
 'computer scientist,software development engineer,research engineer',
 'https://www.geeksforgeeks.org/adobe-interview-experience/',
 NULL),

('Salesforce', 'MNC',
 'Salesforce — Cloud-based software company focused on CRM and enterprise cloud solutions.',
 10.0, 28.0,
 'Sep-Mar',
 'Online Assessment, Technical Rounds (3-4), System Design, HR',
 'Java,Python,Apex,SQL,System Design,Cloud,DSA,OOPs,Git,Communication',
 'software engineer,associate MTS,salesforce developer,cloud engineer',
 'https://www.geeksforgeeks.org/salesforce-interview-experience/',
 NULL),

('Oracle', 'MNC',
 'Oracle — American multinational IT corporation selling database software and cloud infrastructure.',
 8.0, 22.0,
 'Oct-Mar',
 'Online Aptitude + Coding Test, Technical Rounds (3), HR',
 'Java,SQL,PL/SQL,DBMS,DSA,OOPs,System Design,Cloud,Git,Communication',
 'applications engineer,associate software engineer,database developer',
 'https://www.geeksforgeeks.org/oracle-interview-experience/',
 NULL),

('SAP', 'MNC',
 'SAP — Multinational software corporation for enterprise resource planning and business management.',
 8.0, 20.0,
 'Oct-Mar',
 'Online Test, Technical Rounds (2-3), HR',
 'Java,ABAP,SQL,OOPs,System Design,Cloud,DSA,Communication,Git,Analytics',
 'developer associate,associate consultant,SAP developer',
 'https://www.geeksforgeeks.org/sap-interview-experience/',
 NULL),

('IBM', 'MNC',
 'IBM — Multinational IT and consulting corporation pioneering AI, cloud, and quantum computing.',
 6.0, 18.0,
 'Oct-Mar',
 'Online Test (IPAT), Technical Rounds (2-3), HR',
 'Java,Python,SQL,Cloud,AI,DSA,OOPs,Communication,Git,Agile',
 'associate system engineer,software developer,cloud developer,data analyst',
 'https://www.geeksforgeeks.org/ibm-interview-experience/',
 NULL),

('Accenture', 'MNC',
 'Accenture — Global professional services company with capabilities in digital, cloud, and security.',
 4.0, 9.0,
 'Nov-Mar',
 'Cognitive Aptitude Test (CAT), Technical Interview, HR',
 'Java,Python,SQL,OOPs,Communication,Cloud,Agile,Testing,Analytics,Problem Solving',
 'analyst,associate software engineer,cloud engineer,RPA developer',
 'https://www.geeksforgeeks.org/accenture-interview-experience/',
 NULL),

('Deloitte', 'MNC',
 'Deloitte — One of the Big Four accounting and professional services firms globally.',
 6.0, 14.0,
 'Oct-Mar',
 'Aptitude Assessment, Technical Interview, HR',
 'Java,Python,SQL,Analytics,Communication,Cloud,OOPs,Data Analysis,Excel,Problem Solving',
 'analyst,technology consultant,data analyst,associate',
 'https://www.geeksforgeeks.org/deloitte-interview-experience/',
 NULL),

('Walmart Global Tech', 'MNC',
 'Walmart Global Tech — Walmart''s technology division powering retail operations across 10,500+ stores globally.',
 12.0, 28.0,
 'Sep-Feb',
 'Online Coding Test, Technical Rounds (3-4), System Design, HR',
 'Java,DSA,System Design,SQL,AWS,Python,OOPs,Git,Communication,Problem Solving',
 'software development engineer,data engineer,cloud engineer',
 'https://www.geeksforgeeks.org/walmart-labs-interview-experience/',
 NULL),

-- ============================================
-- STARTUPS
-- ============================================
('Startup General', 'Startup',
 'General startup profile — fast-moving companies with broad skill expectations and equity culture.',
 4.0, 15.0,
 'Year Round',
 'Technical Assessment, System Design (light), Culture Fit Interview, HR',
 'Full Stack,React,Node.js,SQL,Python,Git,Communication,Problem Solving,REST API,Agile',
 'full stack developer,software engineer,backend developer,generalist',
 NULL,
 NULL),

('Ola', 'Startup',
 'Ola — India''s largest ride-hailing platform with operations in India, UK, Australia, and New Zealand.',
 8.0, 20.0,
 'Sep-Mar',
 'Online Coding Test, Technical Rounds (3), System Design, HR',
 'Java,Python,DSA,System Design,SQL,AWS,Microservices,React,Git,Communication',
 'software development engineer,data engineer,backend engineer',
 'https://www.geeksforgeeks.org/ola-interview-experience/',
 NULL),

('Nykaa', 'Startup',
 'Nykaa — Indian e-commerce platform for beauty, fashion, and wellness products.',
 6.0, 14.0,
 'Oct-Mar',
 'Coding Test, Technical Interview (2), HR',
 'Java,Python,React,SQL,DSA,System Design,AWS,Git,Communication,OOPs',
 'software engineer,backend developer,fullstack developer,analyst',
 'https://www.geeksforgeeks.org/nykaa-interview-experience/',
 NULL),

('Groww', 'Startup',
 'Groww — Investment platform for stocks, mutual funds, ETFs, and digital gold with 10M+ users.',
 8.0, 20.0,
 'Sep-Mar',
 'Online Coding Test, Technical Rounds (3), System Design, HR',
 'Java,Python,DSA,System Design,SQL,Microservices,AWS,React,Communication,Problem Solving',
 'software development engineer,platform engineer,data engineer',
 'https://www.geeksforgeeks.org/groww-interview-experience/',
 NULL),

('CRED', 'Startup',
 'CRED — Fintech rewards and lifestyle platform for credit card payments with premium user base.',
 10.0, 25.0,
 'Oct-Mar',
 'Coding Assessment, Technical Rounds (3), System Design, Cultural Fit, HR',
 'Java,Python,DSA,System Design,SQL,AWS,Kotlin,Microservices,Communication,Problem Solving',
 'software engineer,backend engineer,platform engineer',
 'https://www.geeksforgeeks.org/cred-interview-experience/',
 NULL),

('Dunzo', 'Startup',
 'Dunzo — Hyperlocal quick delivery platform for groceries, medicines, and more.',
 6.0, 15.0,
 'Year Round',
 'Coding Test, Technical Interview (2), HR',
 'Python,Java,React,SQL,DSA,AWS,Git,Communication,Problem Solving,OOPs',
 'software engineer,backend developer,data analyst',
 NULL,
 NULL),

('Postman', 'Startup',
 'Postman — API platform used by 25M+ developers for building, testing, and collaborating on APIs.',
 10.0, 22.0,
 'Sep-Mar',
 'Online Coding Test, Technical Rounds (3-4), System Design, HR',
 'Java,Python,JavaScript,DSA,System Design,REST API,SQL,Git,Communication,OOPs',
 'software development engineer,platform engineer,API developer',
 'https://www.geeksforgeeks.org/postman-interview-experience/',
 NULL),

('Atlassian', 'Startup',
 'Atlassian — Enterprise software company behind Jira, Confluence, Trello, and Bitbucket.',
 15.0, 35.0,
 'Sep-Feb',
 'Resume Shortlist, Coding Round, Technical Rounds (4), System Design, HR',
 'Java,Python,DSA,System Design,SQL,AWS,Microservices,Git,Communication,Problem Solving',
 'software development engineer,reliability engineer,platform engineer',
 'https://www.geeksforgeeks.org/atlassian-interview-experience/',
 NULL),

('Flipkart', 'Startup',
 'Flipkart — India''s largest e-commerce marketplace, a Walmart subsidiary with 350M+ registered users.',
 10.0, 28.0,
 'Sep-Feb',
 'Online Coding Test (HackerEarth), Technical Rounds (3-4), System Design, HR',
 'Java,Python,DSA,System Design,SQL,Microservices,AWS,Spark,Communication,Problem Solving',
 'software development engineer,data engineer,analyst,ML engineer',
 'https://www.geeksforgeeks.org/flipkart-interview-experience/',
 NULL);
